# Generated by Django 6.0.5 on 2026-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_created_at_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transfer_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
