# Generated by Django 6.0.5 on 2026-06-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_transfer_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
