# Generated by Django 6.0.5 on 2026-06-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('EUR', 'Euro (€)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('CHF', 'Swiss Franc (CHF)')], default='USD', max_length=5),
        ),
    ]
