# Generated by Django 6.0.5 on 2026-06-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
