# Generated by Django 6.0.5 on 2026-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_pin_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_address', models.CharField(max_length=255)),
                ('btc_qr', models.ImageField(upload_to='qr/')),
            ],
        ),
    ]
