# Generated by Django 6.0.5 on 2026-08-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('EUR', 'Euro (€)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('CHF', 'Swiss Franc (CHF)'), ('BRL', 'Brazilian Real (R$)')], default='USD', max_length=5),
        ),
    ]
